version: '3.8'

services:
  my_postgres_db:
    image: postgres:latest
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  post-service:
    depends_on:
      - my_postgres_db
    build:
      context: .
      dockerfile: post-service/Dockerfile
    image: 'my-post-service-iso'
    container_name: 'my-post-service-container'
    environment:
      DB_HOST: my_postgres_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      USER_SERVICE_HOST: user-service:8081
    ports:
      - "8080:8080"
    volumes:
      - ./post-service/migrations:/app/post-service/migrations

  user-service:
    depends_on:
      - my_postgres_db
    build:
      context: .
      dockerfile: user-service/Dockerfile
    image: 'my-user-service-iso'
    container_name: 'my-user-service-container'
    environment:
      DB_HOST: my_postgres_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    ports:
      - "8081:8081"

volumes:
  pg_data:
